apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replica }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
  
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - image: {{ .Values.deployment.image }}
        name: nginx

